# Generated by Django 5.0.6 on 2024-07-11 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_restaurantsubscription'),
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreview',
            name='product',
        ),
        migrations.AddField(
            model_name='driverreview',
            name='deiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='driverreview', to='accounts.driver'),
            preserve_default=False,
        ),
    ]
