# Generated by Django 5.0.6 on 2024-07-11 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driverreview_product_driverreview_deiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverreview',
            old_name='deiver',
            new_name='driver',
        ),
    ]
