# Generated by Django 5.0.6 on 2024-08-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_advertisement_active_advertisement_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
