# Generated by Django 5.0.6 on 2024-08-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_advertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('privacy_policy', models.TextField()),
                ('Terms', models.TextField()),
                ('twiter', models.URLField()),
                ('facebook', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
                ('tiktok', models.URLField()),
                ('whatsapp', models.URLField()),
            ],
        ),
    ]
