# Generated by Django 5.0.6 on 2024-06-09 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_user_address_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('M', 'شهر'), ('6M', 'نصف سنة'), ('Y', 'سنة')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='OrderServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('M', 'شهر'), ('6M', 'نصف سنة'), ('Y', 'سنة')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bankName', models.CharField(max_length=50)),
                ('ccommercialRecordNumber', models.PositiveIntegerField()),
                ('iban', models.CharField(max_length=21)),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantLogo', models.ImageField(upload_to='proven/')),
                ('commercialRecordImage', models.ImageField(upload_to='proven/')),
                ('duration', models.CharField(choices=[('M', 'شهر'), ('6M', 'نصف سنة'), ('Y', 'سنة')], max_length=2)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='ServiceSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/Clients/avatar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='idNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bankName', models.CharField(max_length=50)),
                ('manufactureYear', models.PositiveIntegerField()),
                ('iban', models.CharField(max_length=21)),
                ('companyName', models.CharField(max_length=50)),
                ('carType', models.CharField(max_length=50)),
                ('carLicense', models.ImageField(upload_to='proven/')),
                ('drivingLicense', models.ImageField(upload_to='proven/')),
                ('carFront', models.ImageField(upload_to='cars/')),
                ('carBack', models.ImageField(upload_to='cars/')),
                ('memberSubscription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.membersservicesubscription')),
                ('orderSubscription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.orderservicesubscription')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='RestaurantOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sun', 'الأحد'), ('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الأربعاء'), ('Thu', 'الخميس'), ('Fri', 'الجمعة'), ('Sat', 'السبت')], max_length=3)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
        ),
    ]
