# Generated by Django 5.0.6 on 2024-06-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_car_otprequest_pendingclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingclient',
            name='avatar',
            field=models.ImageField(null=True, upload_to='Client/'),
        ),
    ]
