# Generated by Django 5.0.6 on 2024-06-13 11:14

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_pendingclient_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingclient',
            name='avatar',
            field=models.ImageField(null=True, upload_to=accounts.models.upload_avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_avatar_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PendingDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=accounts.models.upload_avatar_path)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('idNumber', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('fullName', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bankName', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=21)),
                ('companyName', models.CharField(max_length=50)),
                ('carName', models.CharField(max_length=50)),
                ('carCategory', models.CharField(choices=[('إقتصادي', 'Economical'), ('سيدان\\كروس', 'Sedan'), ('كبيرة 6 ركاب', 'Big'), ('أعمال', 'Business')], max_length=12)),
                ('carColor', models.CharField(max_length=50)),
                ('carLicense', models.ImageField(upload_to='proven/')),
                ('drivingLicense', models.ImageField(upload_to='proven/')),
                ('carFront', models.ImageField(upload_to='cars/')),
                ('carBack', models.ImageField(upload_to='cars/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.car')),
                ('memberSubscription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.membersservicesubscription')),
                ('orderSubscription', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.orderservicesubscription')),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendingDriver', to='accounts.otprequest')),
            ],
        ),
        migrations.CreateModel(
            name='PendingRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(null=True, upload_to=accounts.models.upload_avatar_path)),
                ('fullName', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendingRestaurant', to='accounts.otprequest')),
            ],
        ),
    ]
