# Generated by Django 5.0.6 on 2024-06-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_nationality_alter_pendingclient_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='carModel',
        ),
        migrations.AddField(
            model_name='driver',
            name='carModel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendingdriver',
            name='carModel',
            field=models.CharField(default='jj', max_length=50),
            preserve_default=False,
        ),
    ]
