# Generated by Django 5.0.6 on 2024-06-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_driver_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='memberSubscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberSubscription', to='accounts.membersservicesubscription'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orderSubscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderServiceSubscription', to='accounts.orderservicesubscription'),
        ),
    ]
