# Generated by Django 5.0.6 on 2024-06-13 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_driver_membersubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='memberSubscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MembersServiceSubscription', to='accounts.membersservicesubscription'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='orderSubscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='OrderServiceSubscription', to='accounts.orderservicesubscription'),
        ),
        migrations.AlterField(
            model_name='pendingdriver',
            name='memberSubscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.membersservicesubscription'),
        ),
        migrations.AlterField(
            model_name='pendingdriver',
            name='orderSubscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.orderservicesubscription'),
        ),
    ]
