# Generated by Django 5.0.6 on 2024-06-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_driver_membersubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersservicesubscription',
            name='duration',
            field=models.CharField(choices=[('شهر', 'شهر'), ('نصف سنة', 'نصف سنة'), ('سنة', 'سنة')], max_length=8),
        ),
    ]
