# Generated by Django 5.0.6 on 2024-06-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_membersservicesubscription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservicesubscription',
            name='duration',
            field=models.CharField(choices=[('شهر', 'شهر'), ('نصف سنة', 'نصف سنة'), ('سنة', 'سنة')], max_length=8),
        ),
    ]
