# Generated by Django 5.0.6 on 2024-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_orderservicesubscription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingdriver',
            name='oldPhone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
