# Generated by Django 5.0.6 on 2024-06-14 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pendingdriver_oldphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdriver',
            name='otp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendingDriver', to='accounts.otprequest'),
        ),
    ]
