# Generated by Django 5.0.6 on 2024-06-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_pendingdriver_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('شهر', 'شهر'), ('نصف سنة', 'نصف سنة'), ('سنة', 'سنة')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='duration',
        ),
        migrations.DeleteModel(
            name='PendingRestaurant',
        ),
    ]
