# Generated by Django 5.0.6 on 2024-06-15 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_restaurantsubscription_remove_restaurant_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('idNumber', models.CharField(max_length=10)),
                ('birth', models.DateField()),
                ('fullName', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bankName', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=21)),
                ('restaurantName', models.CharField(max_length=50)),
                ('restaurantLogo', models.ImageField(upload_to='proven/')),
                ('commercialRecordImage', models.ImageField(upload_to='proven/')),
                ('oldPhone', models.CharField(default=None, max_length=10, null=True)),
                ('otp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendingRestaurant', to='accounts.otprequest')),
            ],
        ),
    ]
