# Generated by Django 5.0.6 on 2024-06-15 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_pendingrestaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrestaurant',
            name='restaurantSubscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurantsubscription'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantSubscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurantsubscription'),
            preserve_default=False,
        ),
    ]
