# Generated by Django 5.0.6 on 2024-06-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_pendingrestaurant_restaurantsubscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
