# Generated by Django 5.0.6 on 2024-06-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_driver_enabled_user_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='ccommercialRecordNumber',
            new_name='commercialRecordNumber',
        ),
    ]
