# Generated by Django 5.0.6 on 2024-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_rename_ccommercialrecordnumber_restaurant_commercialrecordnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrestaurant',
            name='commercialRecordNumber',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
