# Generated by Django 5.0.6 on 2024-06-15 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_pendingrestaurant_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrestaurant',
            name='otp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pendingRestaurant', to='accounts.otprequest'),
        ),
    ]
