# Generated by Django 5.0.6 on 2024-06-15 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_pendingrestaurant_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrestaurant',
            name='restaurantSubscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantSubscription', to='accounts.restaurantsubscription'),
        ),
    ]
