# Generated by Django 5.0.6 on 2024-06-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantopening',
            name='Rest_time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantopening',
            name='Rest_time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
