# Generated by Django 5.0.6 on 2024-06-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_restaurantopening_rest_time_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantOpening',
        ),
    ]
