# Generated by Django 5.0.6 on 2024-06-27 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('titleArgs', models.JSONField(default=list)),
                ('body', models.TextField()),
                ('bodyArgs', models.JSONField(default=list)),
                ('sentAt', models.DateTimeField(auto_now_add=True)),
                ('localized', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sentAt'],
            },
        ),
    ]
