# Generated by Django 5.0.6 on 2024-06-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantStatus',
            field=models.BooleanField(default=True),
        ),
    ]
