# Generated by Django 5.0.6 on 2024-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_notification_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurantSubscription',
        ),
        migrations.AlterField(
            model_name='pendingrestaurant',
            name='restaurantSubscription',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='RestaurantSubscription',
        ),
    ]
