# Generated by Django 5.0.6 on 2024-07-10 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_restaurant_restaurantsubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('restaurant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantSubscription', to='accounts.restaurant')),
            ],
        ),
    ]
