# Generated by Django 5.0.6 on 2024-08-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_remove_driver_membersubscription_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMBERS', 'Members'), ('ORDERS', 'Orders'), ('RESTAURANT', 'Restaurant')], max_length=10)),
                ('duration', models.CharField(choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='pendingdriver',
            name='memberSubscription',
            field=models.CharField(blank=True, choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingdriver',
            name='orderSubscription',
            field=models.CharField(blank=True, choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pendingrestaurant',
            name='restaurantSubscription',
            field=models.CharField(choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=10),
        ),
        migrations.CreateModel(
            name='DriverOrderSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverOrderSubscription', to='accounts.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTripSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('30', 'MONTH'), ('182', 'SIX_MONTH'), ('364', 'YEAR')], max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverTripSubscription', to='accounts.driver')),
            ],
        ),
        migrations.DeleteModel(
            name='DriverSubscription',
        ),
        migrations.DeleteModel(
            name='MembersServiceSubscription',
        ),
        migrations.DeleteModel(
            name='OrderServiceSubscription',
        ),
    ]
