# Generated by Django 5.0.6 on 2024-08-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_subscriptionconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverordersubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driverordersubscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivertripsubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='drivertripsubscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantsubscription',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantsubscription',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
