# Generated by Django 5.0.6 on 2024-08-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_driverordersubscription_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('subscriptions', 'Subscriptions Control'), ('Driver', 'Subscriptions Control'))},
        ),
    ]
