# Generated by Django 5.0.6 on 2024-08-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantsubscription',
            name='duration',
            field=models.CharField(max_length=8),
        ),
    ]
