# Generated by Django 5.0.6 on 2024-08-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_restaurantsubscription_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Car Trip')),
                ('price_per_km', models.FloatField(blank=True, null=True)),
                ('less_than_three_km', models.FloatField(blank=True, null=True)),
                ('between_three_and_six_km', models.FloatField(blank=True, null=True)),
                ('more_than_six_km', models.FloatField(blank=True, null=True)),
                ('car_category', models.CharField(max_length=50)),
                ('average_speed', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='driver',
            name='carCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carcategory'),
        ),
    ]
