# Generated by Django 5.0.6 on 2024-08-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_carcategory_alter_driver_carcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdriver',
            name='carCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.carcategory'),
        ),
    ]
