# Generated by Django 5.0.6 on 2024-08-25 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_renewrestaurantsubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RenewRestaurantSubscription',
        ),
    ]
