# Generated by Django 5.0.6 on 2024-08-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_renewrestaurantsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='companyName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
