# Generated by Django 5.0.6 on 2024-08-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_driver_companyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notificationEnabled',
            field=models.BooleanField(default=True),
        ),
    ]
