# Generated by Django 5.0.6 on 2024-09-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minimumOrder',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
