# Generated by Django 5.0.6 on 2024-09-07 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_restaurant_minimumorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='minimumOrder',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8),
        ),
    ]
