# Generated by Django 5.0.6 on 2024-09-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_restaurant_minimumorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('subscriptions', 'التحكم بطلبات الإشتراك'), ('Driver', 'التحكم بالمناديب'), ('Restaurants', 'التحكم بالمطاعم'), ('Clients', 'التحكم بالعملاء'), ('config', 'التحكم بالإعدادات'), ('Financial', 'التحكم بالقوائم المالية'), ('Categories', 'التحكم بالتصنيفات'), ('Coupon', 'التحكم بالكوبونات'), ('Statistics', 'الوصول للالإحصائيات'), ('CommonQuestions', 'التحكم بالأسئلة الشائعة'), ('Ads', 'التحكم بالإعلانات'), ('Support', 'التحكم بالدعم'))},
        ),
    ]
