# Generated by Django 5.0.6 on 2024-08-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_renewrestaurantsubscription'),
        ('wallet', '0002_paymentorder_amount_paymenttrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenewSubscription', to='accounts.restaurantsubscription')),
            ],
        ),
    ]
