# Generated by Django 5.0.6 on 2024-08-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_delete_renewrestaurantsubscription'),
        ('wallet', '0004_driverordersubscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTripSubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.BooleanField(default=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RenewTripSubscription', to='accounts.drivertripsubscription')),
            ],
        ),
    ]
