# Generated by Django 5.0.6 on 2024-09-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_drivertripsubscriptionpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverordersubscriptionpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drivertripsubscriptionpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttrip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantsubscriptionpayment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
