# Generated by Django 5.0.6 on 2024-09-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_driverordersubscriptionpayment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='last_withdrawal',
            field=models.DateTimeField(null=True),
        ),
    ]
