# Generated by Django 5.0.6 on 2024-06-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_product_hours_service_product_minimumorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='accessory_products',
            field=models.ManyToManyField(related_name='products', to='restaurant.accessoryproduct'),
        ),
    ]
