# Generated by Django 5.0.6 on 2024-06-18 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_accessoryproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accessory_products',
        ),
        migrations.AddField(
            model_name='accessoryproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.product'),
            preserve_default=False,
        ),
    ]
