# Generated by Django 5.0.6 on 2024-06-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_product_category_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
