# Generated by Django 5.0.6 on 2024-06-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
