# Generated by Django 5.0.6 on 2024-06-19 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_delete_restaurantopening'),
        ('restaurant', '0010_commonquestion_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sun', 'الأحد'), ('Mon', 'الاثنين'), ('Tue', 'الثلاثاء'), ('Wed', 'الأربعاء'), ('Thu', 'الخميس'), ('Fri', 'الجمعة'), ('Sat', 'السبت')], max_length=3)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('Rest_time_start', models.TimeField(blank=True, null=True)),
                ('Rest_time_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant')),
            ],
        ),
    ]
