# Generated by Django 5.0.6 on 2024-06-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_restaurantopening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='customer',
            new_name='client',
        ),
    ]
