# Generated by Django 5.0.6 on 2024-06-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_customer_reviews_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='client',
            new_name='customer',
        ),
    ]
