# Generated by Django 5.0.6 on 2024-06-19 20:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_delete_restaurantopening'),
        ('restaurant', '0014_rename_customer_reviews_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='رسالة')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم المنتج')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاريخ الإنشاء')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='الزبون')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.restaurant', verbose_name='المتجر')),
            ],
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
