# Generated by Django 5.0.6 on 2024-06-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_review_delete_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='store',
            new_name='restaurant',
        ),
    ]
