# Generated by Django 5.0.6 on 2024-07-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_notification_order'),
        ('restaurant', '0018_alter_productreview_product_restaurantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonquestion',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurantcommonquestion', to='accounts.restaurant'),
        ),
    ]
