# Generated by Django 5.0.6 on 2024-09-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0019_alter_commonquestion_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='minimumOrder',
        ),
    ]
