# Generated by Django 5.0.6 on 2024-06-27 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_tax_alter_order_coupon_delete_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deiver',
            new_name='driver',
        ),
    ]
