# Generated by Django 5.0.6 on 2024-06-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_deiver_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
