# Generated by Django 5.0.6 on 2024-07-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartitem_note_orderitem_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tax',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('WALLET', 'wallet'), ('E_PAYMENT', 'e-payment')], max_length=15, null=True),
        ),
    ]
