# Generated by Django 5.0.6 on 2024-07-10 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_order_tax_alter_order_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaccessory',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='unit_price',
        ),
    ]
