# Generated by Django 5.0.6 on 2024-07-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_cartaccessory_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaccessory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
