# Generated by Django 5.0.6 on 2024-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_tripcar_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
