# Generated by Django 5.0.6 on 2024-07-14 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_trip_distance_alter_trip_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.coupon'),
        ),
    ]
