# Generated by Django 5.0.6 on 2024-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_driverlat_remove_order_driverlng_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripcar',
            name='name',
        ),
        migrations.AddField(
            model_name='tripcar',
            name='car_category',
            field=models.CharField(choices=[('إقتصادي', 'Economical'), ('سيدان\\كروس', 'Sedan'), ('كبيرة 6 ركاب', 'Big'), ('أعمال', 'Business')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
