# Generated by Django 5.0.6 on 2024-08-17 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_driverordersubscription_enabled_and_more'),
        ('order', '0012_remove_tripcar_name_tripcar_car_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driverCoupon', to='accounts.driver'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantCoupon', to='accounts.restaurant'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('عام', 'General'), ('مطعم', 'Restaurant'), ('مندوب', 'Driver')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
