# Generated by Django 5.0.6 on 2024-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_coupon_driver_coupon_restaurant_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripcar',
            name='between_three_and_six_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripcar',
            name='less_than_three_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tripcar',
            name='more_than_six_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tripcar',
            name='car_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tripcar',
            name='price_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
