# Generated by Django 5.0.6 on 2024-08-21 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_carcategory_alter_driver_carcategory'),
        ('order', '0014_tripcar_between_three_and_six_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripcar', to='accounts.carcategory'),
        ),
    ]
