# Generated by Django 5.0.6 on 2024-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_alter_trip_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceledBy',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Driver'), ('CLIENT', 'Client'), ('RESTAURANT', 'Restaurant')], max_length=50, null=True),
        ),
    ]
