# Generated by Django 5.0.6 on 2024-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_canceledby'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkoutAt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
