# Generated by Django 5.0.6 on 2024-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_order_status_alter_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='canceledBy',
        ),
        migrations.AddField(
            model_name='order',
            name='rejectedBy',
            field=models.CharField(blank=True, choices=[('DRIVER', 'Driver'), ('RESTAURANT', 'Restaurant')], max_length=50, null=True),
        ),
    ]
