# Generated by Django 5.0.6 on 2024-08-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_canceledby_order_rejectedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryCost',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
