# Generated by Django 5.0.6 on 2024-08-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_deliverycost'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfig',
            name='average_speed',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='between_three_and_six_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='less_than_three_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='more_than_six_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderconfig',
            name='price_per_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
