# Generated by Django 5.0.6 on 2024-09-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_orderconfig_average_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DRIVER_ACCEPTED', 'Driver Accepted'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('RESTAURANT_COMPLETED', 'Restaurant Completed'), ('ON_WAY', 'On Way'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DRIVER_ACCEPTED', 'Driver Accepted'), ('ACCEPTED', 'Accepted'), ('IN_PROGRESS', 'In Progress'), ('RESTAURANT_COMPLETED', 'Restaurant Completed'), ('ON_WAY', 'On Way'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], max_length=20),
        ),
    ]
